# permissions for end users to view foos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-test
    app.kubernetes.io/managed-by: kustomize
  name: foo-viewer-role
rules:
- apiGroups:
  - mytestgroup.mytest.domain
  resources:
  - foos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mytestgroup.mytest.domain
  resources:
  - foos/status
  verbs:
  - get
