apiVersion: mytestgroup.mytest.domain/v1
kind: Foo
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-test
    app.kubernetes.io/managed-by: kustomize
  name: foo-sample
spec:
  # TODO(user): Add fields here
